name: Tests

on:
  push:
  pull_request:
  schedule:
    # Automatically run the first of each month
    - cron: '0 12 1 * *'

jobs:
  testing:
    strategy:
      matrix:
        php: [7.3, 7.4, 8.0, 8.1]
        laravel: [7, 8, 9]
        exclude:
          - php: 8.1
            laravel: 7
          - php: 7.3
            laravel: 8
          - php: 7.3
            laravel: 9
          - php: 7.4
            laravel: 9

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, dom, fileinfo

      - name: Install orchestra/database:6
        if: matrix.laravel == 9
        run: composer require orchestra/database:^6

      - name: Install Dependencies
        run: |
          composer require "illuminate/contracts:^${{ matrix.laravel }}" --no-interaction --no-update
          composer install --prefer-dist --no-interaction --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit
